kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service-stage
  namespace: train-stage
spec:
  type: NodePort
  selector:
    app: train-schedule-stage
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30090



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment-stage
  namespace: train-stage
  labels:
    app: train-schedule-stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule-stage
  template:
    metadata:
      labels:
        app: train-schedule-stage
    spec:
      containers:
      - name: train-schedule-stage
        image: grocamador/cicd-demo:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
